
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-happycows-s23-6pm-3
owner: ucsb-cs156-s23
repo_name: proj-happycows-s23-6pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pconrad-patch-1","number":44,"title":"Update 33-frontend-pr-mutation-testing.yml","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/44"},{"author":{"id":"MDQ6VXNlcjczNzY2Mzgx","is_bot":false,"login":"nhs-wobuzhidao","name":""},"headRefName":"Anoushka-toastdegRate","number":43,"title":"Anoushka toastdeg rate","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/43"},{"author":{"id":"MDQ6VXNlcjg3Mzk1Njk1","is_bot":false,"login":"MrJacobEisner","name":"Jacob Eisner"},"headRefName":"je-priceChange-frontend-changes","number":39,"title":"JE Implemented frontend calls and tests","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/39"},{"author":{"id":"MDQ6VXNlcjg3Mzk1Njk1","is_bot":false,"login":"MrJacobEisner","name":"Jacob Eisner"},"headRefName":"je-priceChange-commons","number":38,"title":"JE price change commons","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/38"},{"author":{"id":"MDQ6VXNlcjg3Mzk1Njk1","is_bot":false,"login":"MrJacobEisner","name":"Jacob Eisner"},"headRefName":"je-implement-buy-operation","number":36,"title":"JE implement buy operation","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/36"},{"author":{"id":"MDQ6VXNlcjg3Mzk1Njk1","is_bot":false,"login":"MrJacobEisner","name":"Jacob Eisner"},"headRefName":"je-priceChange-form-table","number":35,"title":"JE Completed priceChange form, table, and tests","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/35"}]
