
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-happycows-s23-6pm-3
owner: ucsb-cs156-s23
repo_name: proj-happycows-s23-6pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjg3Mzk1Njk1","is_bot":false,"login":"MrJacobEisner","name":"Jacob Eisner"},"headRefName":"ad-je-cow-lot-integration","number":62,"title":"Ad Je - Cow lot integration with frontend and deaths","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/62"},{"author":{"id":"MDQ6VXNlcjQ0MDc2MTUx","is_bot":false,"login":"awaang","name":"Amy Wang"},"headRefName":"aw-farmland-interface","number":60,"title":"AW Farmland interface","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/60"},{"author":{"id":"MDQ6VXNlcjIxMTY1NjEy","is_bot":false,"login":"epuzio","name":"E. Puzio"},"headRefName":"ep-start-time","number":59,"title":"FEATURE: Added end date to UserCommons and Commons, cow health and cow milking jobs only run before end date/after start date","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/59"}]
