
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-happycows-s23-6pm-3
owner: ucsb-cs156-s23
repo_name: proj-happycows-s23-6pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjIxMTY1NjEy","is_bot":false,"login":"epuzio","name":"E. Puzio"},"headRefName":"ep-start-time","number":59,"title":"FEATURE: Added End Date, cows are not milked and cow health does not degrade after end date","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/59"},{"author":{"id":"MDQ6VXNlcjczNzY2Mzgx","is_bot":false,"login":"nhs-wobuzhidao","name":""},"headRefName":"Anoushka-jobsubmission","number":58,"title":"Frontend: Added Jobs Toast Notification","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/58"},{"author":{"id":"MDQ6VXNlcjg3Mzk1Njk1","is_bot":false,"login":"MrJacobEisner","name":"Jacob Eisner"},"headRefName":"je-cowLots-frontend","number":57,"title":"Je cow lots frontend","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/57"},{"author":{"id":"MDQ6VXNlcjg3Mzk1Njk1","is_bot":false,"login":"MrJacobEisner","name":"Jacob Eisner"},"headRefName":"je-get-cowLots-endpoint","number":56,"title":"Je get cow lots endpoint","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/56"},{"author":{"id":"MDQ6VXNlcjc3Njk4NzM3","is_bot":false,"login":"MaximillianStewart","name":""},"headRefName":"Max-LinkFix","number":54,"title":"ms - updated link to this repository","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/54"},{"author":{"id":"MDQ6VXNlcjU2MDkyODkx","is_bot":false,"login":"Anshuman-UCSB","name":"Anshuman Dash"},"headRefName":"ad-cow-lots-health-degredation","number":51,"title":"Implement cowlots into health degredation job","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/51"},{"author":{"id":"MDQ6VXNlcjczNzY2Mzgx","is_bot":false,"login":"nhs-wobuzhidao","name":""},"headRefName":"Anoushka-commonstoastdeg","number":49,"title":"added deg rate to admin commons toast","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/49"},{"author":{"id":"MDQ6VXNlcjg3Mzk1Njk1","is_bot":false,"login":"MrJacobEisner","name":"Jacob Eisner"},"headRefName":"je-priceChange-frontend-changes","number":39,"title":"JE Implemented frontend calls and tests","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/39"},{"author":{"id":"MDQ6VXNlcjg3Mzk1Njk1","is_bot":false,"login":"MrJacobEisner","name":"Jacob Eisner"},"headRefName":"je-implement-buy-operation","number":36,"title":"JE implement buy operation","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/36"}]
