
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-happycows-s23-6pm-3
owner: ucsb-cs156-s23
repo_name: proj-happycows-s23-6pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjg3Mzk1Njk1","is_bot":false,"login":"MrJacobEisner","name":"Jacob Eisner"},"headRefName":"je-implement-sell-operation","number":37,"title":"Je implement sell operation","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/37"},{"author":{"id":"MDQ6VXNlcjg3Mzk1Njk1","is_bot":false,"login":"MrJacobEisner","name":"Jacob Eisner"},"headRefName":"je-implement-buy-operation","number":36,"title":"Je implement buy operation","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/36"},{"author":{"id":"MDQ6VXNlcjg3Mzk1Njk1","is_bot":false,"login":"MrJacobEisner","name":"Jacob Eisner"},"headRefName":"je-priceChange-form-table","number":35,"title":"Completed priceChange form, table, and tests","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/35"},{"author":{"id":"MDQ6VXNlcjg3Mzk1Njk1","is_bot":false,"login":"MrJacobEisner","name":"Jacob Eisner"},"headRefName":"je-add-priceChange-fixtures","number":34,"title":"Added Commons PriceChange Fixtures","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/34"},{"author":{"id":"MDQ6VXNlcjg3Mzk1Njk1","is_bot":false,"login":"MrJacobEisner","name":"Jacob Eisner"},"headRefName":"je-priceChange-entity-repository","number":33,"title":"Implemented price change methods and attributes","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/33"},{"author":{"id":"MDQ6VXNlcjU2MDkyODkx","is_bot":false,"login":"Anshuman-UCSB","name":"Anshuman Dash"},"headRefName":"ad-cow-lot-buy","number":32,"title":"Ad cow lot buy","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/32"},{"author":{"id":"MDQ6VXNlcjc3Njk4NzM3","is_bot":false,"login":"MaximillianStewart","name":""},"headRefName":"Max-MilkPrice","number":30,"title":"ms - updated storybook component and added extra parameter","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/30"},{"author":{"id":"MDQ6VXNlcjU2MDkyODkx","is_bot":false,"login":"Anshuman-UCSB","name":"Anshuman Dash"},"headRefName":"ad-cow-lots","number":27,"title":"Add entity and repository for CowLot entry","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-3/pull/27"}]
